changes to support Jakartaee10 jars and Glassfish 7
arquillian/arquillian-container-glassfish6 pull request #11
Opened 2022-04-12 06:55 UTC by gurunrao

changes to support Jakartaee10 jars and Glassfish 7.

2022-04-12 12:29 UTC, starksm64 commented
In the #12 PR is have reorganized the artifacts and modules to be generic, and the version reflects the GlassFish version. Once this PR is merged, I can update the master branch to use the same organization.

2022-04-12 12:59 UTC, starksm64 requested changes

2022-04-12 13:23 UTC, gurunrao commented on glassfish-common/pom.xml
> +    <artifactId>arquillian-parent-glassfish7</artifactId>
There is an overlap in changes made by current PR and PR #12 (which was open post PR #11), example similar changes include making package generic from glassfish_6 to glassfish,  I will wait for PR#12 to be merged and resolve conflicts post that.

2022-04-12 13:28 UTC, gurunrao commented on pom.xml
> +    <version.arquillian_core>1.7.0.Final-SNAPSHOT</version.arquillian_core>
Based on https://repo1.maven.org/maven2/org/jboss/arquillian/container/arquillian-container-spi/ shall we use `1.7.0.Alpha9`

2022-04-12 13:31 UTC, gurunrao commented
PR #12  needs to be merged and conflicts needs to be resolved before PR can be merged.

2022-04-12 20:02 UTC, starksm64 commented
If I try to build your fork with SE 11, I'm seeing that the org.glassfish.hk2:hk2-locator:jar:3.0.0-M1 artifact cannot be found:

```
[ERROR] Failed to execute goal on project arquillian-glassfish6-common: Could not resolve dependencies for project org.jboss.arquillian.container:arquillian-glassfish6-common:jar:1.0.0.Final-SNAPSHOT: org.glassfish.hk2:hk2-locator:jar:3.0.0-M1 was not found in https://jakarta.oss.sonatype.org/content/repositories/staging/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of jakarta-nexus-staging has elapsed or updates are forced -> [Help 1]
```

2022-04-13 03:09 UTC, gurunrao commented
> If I try to build your fork with SE 11, I'm seeing that the org.glassfish.hk2:hk2-locator:jar:3.0.0-M1 artifact cannot be found:
> 
> ```
> [ERROR] Failed to execute goal on project arquillian-glassfish6-common: Could not resolve dependencies for project org.jboss.arquillian.container:arquillian-glassfish6-common:jar:1.0.0.Final-SNAPSHOT: org.glassfish.hk2:hk2-locator:jar:3.0.0-M1
> was not found in https://jakarta.oss.sonatype.org/content/repositories/staging/ during a previous attempt. This failure was
> cached in the local repository and resolution is not reattempted until the update interval of jakarta-nexus-staging has
> elapsed or updates are forced -> [Help 1]
> ```
currently not able to reproduce the issue, attaching [logs](https://github.com/arquillian/arquillian-container-glassfish6/files/8477904/acg_build.log)

2022-04-13 04:05 UTC, gurunrao commented on glassfish-common/pom.xml
> +    <artifactId>arquillian-parent-glassfish7</artifactId>
done.

2022-04-14 15:51 UTC, gurunrao commented
> failure

^ failure is not reproducible at CI run https://ci.eclipse.org/jakartaee-tck/job/guru/job/cditck-porting-guru/job/jakartaee-10/81/consoleText

2022-04-18 14:01 UTC, gurunrao commented
@starksm64  - `org.glassfish.hk2:hk2-locator:jar:3.0.0-M1 artifact cannot be found`  error is not seen in local setup or CI.

2022-04-20 01:19 UTC, gurunrao commented
@starksm64  - Let me know if the PR can be merged, as review comments are not open?

2022-04-20 19:42 UTC, starksm64 approved these changes

2022-04-20 19:43 UTC, merged

2022-04-20 19:44 UTC, starksm64 commented
I merged it. We still need to get the main branch CI config updated and working.